Update zendnnl_pr.yml for AI gtests
ZENAI-2061

Change-Id: I98ecbf327298a48fc05ea6c3ce8a30d4f97ad201
Signed-off-by: Kiriti Pendyala <kiriti.pendyala@amd.com>

Signed-off-by: Pendyala, Kiriti <Kiriti.Pendyala@amd.com>

diff --git a/.github/workflows/zendnnl_pr.yml b/.github/workflows/zendnnl_pr.yml
--- a/.github/workflows/zendnnl_pr.yml
+++ b/.github/workflows/zendnnl_pr.yml
@@ -305,10 +305,10 @@ jobs:
           echo "ZenDNNL gtests passed!"
         fi
 
-        echo "Running ai_gtests with filter: $AI_GTEST_FILTER"
+        echo "Running ai_gtests with filter: presub"
         
         # Run the ai_gtests with configurable parameters
-        ./install/gtests/gtests --gtest_filter=$AI_GTEST_FILTER |& tee $WORKSPACE/ai_gtest_output.log
+        ./install/gtests/gtests --ai_test_mode pre-sub --gtest_filter="AITests/*:-AITests/TestBatch*" |& tee $WORKSPACE/ai_gtest_output.log
         
         # Check for test failures
         if grep -F -q "[  FAILED  ]" "$WORKSPACE/ai_gtest_output.log"; then
@@ -648,6 +648,20 @@ jobs:
           exit 1
         else
           echo "ZenDNNL gtests passed!"
+        fi
+        
+        echo "Running ai_gtests with filter: postsub"
+        
+        # Run the ai_gtests with configurable parameters
+        ./install/gtests/gtests --ai_test_mode post-sub --gtest_filter="AITests/*:-AITests/TestBatch*" |& tee $WORKSPACE/ai_gtest_output.log
+        
+        # Check for test failures
+        if grep -F -q "[  FAILED  ]" "$WORKSPACE/ai_gtest_output.log"; then
+          echo "ZenDNNL ai_gtests failed!"
+          cat "$WORKSPACE/ai_gtest_output.log"
+          exit 1
+        else
+          echo "ZenDNNL ai_gtests passed!"
         fi
       shell: bash
 
