ZENAI-2061 Refactor ZenDNNL CI workflow for clarity and updates

diff --git a/.github/workflows/zendnnl_pr.yml b/.github/workflows/zendnnl_pr.yml
--- a/.github/workflows/zendnnl_pr.yml
+++ b/.github/workflows/zendnnl_pr.yml
@@ -1,4 +1,4 @@
-name: ZenDNNL PR Build
+name: ZenDNNL PR CI 
 
 on:
   push:
@@ -231,7 +231,7 @@ jobs:
         echo "Workspace cleanup completed"
       shell: bash
   trigger-zenTorch-ZenDNNL:
-    needs: [Zendnnl_build_PR]
+    #needs: [Zendnnl_build_PR]
     runs-on: amd-zenai-arc-xsmall-dind
     if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
     steps:
@@ -250,35 +250,40 @@ jobs:
             }
           }'
        shell: bash
-  check-status:
-     needs: [trigger-zenTorch-ZenDNNL]
-     runs-on: amd-zenai-arc-xsmall-dind
-     steps:
-      - name:  ZenTorch_ZenDNNL status
-        run: |
-          repo_pytorch="AMD-Zenai/ZenDNN_PyTorch_Plugin"
-          zendnnl_sha="${{ github.event.pull_request.head.sha || github.sha }}"
-          echo "Checking ZenTorch_ZenDNNL CI status for commit: $zendnnl_sha"
+  check-zenTorch-status:
+   needs: [trigger-zenTorch-ZenDNNL]
+   runs-on: amd-zenai-arc-xsmall-dind
+   steps:
+    - name: Check PyTorch & TensorFlow plugin CI statuses
+      env:
+        GH_TOKEN: ${{ secrets.ZIAIE_PAT }}
+        REPO_ZENDNN: AMD-Zenai/ZenDNN
+        COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
+      run: |
+        echo "Checking ZenTorch_Zendnnl CI status for commit $COMMIT_SHA..."
 
-          # Wait a bit to allow status to update
-          sleep 120
+        while true ; do
+          status=$(curl -s -H "Authorization: token $GH_TOKEN" \
+            "https://api.github.com/repos/$REPO_ZENDNN/commits/$COMMIT_SHA/status" \
+            | jq -r '.statuses[] | select(.context=="AMD-Zenai/ZenDNN_PyTorch_Plugin CI") | .state' | tail -n 1)
 
-          # Fetch statuses for that commit
-          state=$(curl -s -H "Authorization: token ${{ secrets.ZIAIE_PAT }}" \
-            "https://api.github.com/repos/AMD-Zenai/ZenDNN/statuses/$zendnnl_sha" | \
-            jq -r 'map(select(.context=="AMD-Zenai/ZenDNN_PyTorch_Plugin CI")) | .[0].state')
+          echo "Attempt $i: ZenTorch-ZenDNNL CI status = $status"
 
-          echo "ZenTorch_ZenDNNL status: $state"
-
-          if [[ "$state" != "success" ]]; then
-            echo " ZenTorch_ZenDNNL failed — marking ZenDNNL as failed"
-            exit 1
-          else
-            echo "ZenTorch_ZenDNNL passed — ZenDNNL remains green"
+          if [[ "$status" == "success" ]]; then
+            echo "ZenTorch-ZenDNNL workflow succeeded."
+            exit 0
           fi
 
+          if [[ "$status" == "failure" ]]; then
+            echo "ZenTorch-ZenDNNL workflow failed."
+            exit 1
+          fi
 
-  Zendnnl_build_push: 
+          sleep 30
+        done
+
+        
+  Zendnnl_build_Push: 
    runs-on: zendnnl_presub_server
    if: ${{ github.event_name == 'push' }}
    env:
@@ -489,7 +494,7 @@ jobs:
   asan-build:
    runs-on: zendnnl_presub_server
    if: ${{ github.event_name == 'push' }}
-   needs:  Zendnnl_build_push
+   #needs: Zendnnl_build_Push
    env:
       PYTHON_VERSION: ${{ github.event.inputs.python_version || '3.10' }}
       CMAKE_VERSION: ${{ github.event.inputs.cmake_version || '4.0.0' }}
@@ -652,6 +657,16 @@ jobs:
         rm -f $WORKSPACE/asan_gtest_output.log
         echo "Workspace cleanup completed"
       shell: bash
+ 
+ 
+
+
+      
+ 
+ 
+
+
+      
  
  
 
